#!/bin/bash

# Simple tool to change wordpress admin password
# Basic usage: ./wpresetadminpassword database_name database_user_name 
# Example: ./wpresetadminpassword wordpress wordpress_blog
# Example: ./wpresetadminpassword wordpress wordpress_blog MD5_HASH_PASSWORD

db=$1
db_user=$2

prefix="wp_"
login="admin"

if [ -n "$1" -a -n "$2" ]
then

    until mysql -u $db_user -p$mysqlRootPassword  -e "select 1 from dual where 0"
       read -p "Can't connect, please retry: " mysqlRootPassword
    done

    exit;

     mysql -u $db_user -p

    read -s -p "Enter MYSQL password: " mysqlpass
    echo ""
    mysql -b -u $db_user -p${mysqlpass} $db
    if [ $? -ne 0 ]; 
    then
      exit
    fi

    echo -e "\nCurrent hash password is:"
    sql="SELECT user_login, user_pass FROM ${prefix}users WHERE user_login='${login}' LIMIT 1";
    res=`mysql -u $db_user -p"$mysqlpass" $db -e "$sql"`
    echo $res

    if [ -n "$3" ]
    then
       echo "Setting $login password to hash: $3"
       md5=$3
    else 
       read -s -p "Enter $login password: " newpass
       echo ""
       md5=`echo -n $newpass | md5sum | cut -b-32`
    fi

    sqlupdate="UPDATE ${prefix}users SET user_pass='${md5}' WHERE user_login='${login}' LIMIT 1";
    mysql -u $db_user -p"$mysqlpass" $db -e "$sqlupdate"

    echo "Current hash password is:"
    sql="SELECT user_login, user_pass FROM ${prefix}users WHERE user_login='${login}' LIMIT 1";
    mysql -u $db_user -p"$mysqlpass" $db -e "$sql"
else
    echo "Usage: ./`basename $0` database_name database_user_name password_hash(optionally)"
    echo "Example: ./`basename $0` database_name database_user"
    echo "Example: ./`basename $0` database_name database_user MD5_HASH_PASSWORD"
fi
